// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbR6mPi5JcuvmBr_4ZDRwyq_CyDrbo01Q',
    appId: '1:480759107326:web:8009bf3d313cccb8cbdfaf',
    messagingSenderId: '480759107326',
    projectId: 'swidshop-d8ccf',
    authDomain: 'swidshop-d8ccf.firebaseapp.com',
    storageBucket: 'swidshop-d8ccf.firebasestorage.app',
    measurementId: 'G-6NV6JK6GP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYV5P9L2pyhWOAbelxr5vwtfEOiHKuFqw',
    appId: '1:480759107326:android:de7f67b10d829539cbdfaf',
    messagingSenderId: '480759107326',
    projectId: 'swidshop-d8ccf',
    storageBucket: 'swidshop-d8ccf.firebasestorage.app',
  );
}
